name: Test dev3000 on Alpine Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  reproduce-bug:
    name: Test dev3000 on Alpine Linux
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install system dependencies
        run: |
          apk update
          apk add --no-cache nodejs npm git bash curl lsof

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install app dependencies
        run: pnpm install

      - name: Install dev3000 globally (original version)
        run: pnpm install -g dev3000

      - name: Run dev3000 --servers-only and test startup
        shell: bash
        run: |
          # Start dev3000 in background and test startup on Alpine
          d3k --servers-only > d3k_output.log 2>&1 &
          DEV_PID=$!
          echo "d3k PID: $DEV_PID"
          
          # Wait for startup
          sleep 30
          
          # Check if MCP server is running
          if curl -f -s http://localhost:3684/logs > /dev/null; then
            echo "✅ MCP server started successfully on Alpine"
          else
            echo "❌ MCP server failed to start"
            cat d3k_output.log
            exit 1
          fi
          
          # Display output
          echo "--- d3k OUTPUT ---"
          cat d3k_output.log
          echo "--- END OUTPUT ---"
          
          # Gracefully stop dev3000
          kill $DEV_PID
          wait $DEV_PID || true

      - name: Check for log file and display contents
        shell: bash
        if: always()
        run: |
          # Find the latest dev3000 log in temp dir (Alpine uses /tmp)
          tempDir="/tmp"
          logPattern="${tempDir}/dev3000-logs/dev3000-*.log"
          if ls $logPattern &> /dev/null; then
            latestLog=$(ls -t $logPattern | head -n 1)
            echo "Found log file: $latestLog"
            echo "--- LOG CONTENTS ---"
            cat "$latestLog"
            echo "--- END LOG ---"
          else
            echo "No dev3000 log file found in $tempDir/dev3000-logs/"
          fi